export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCHING_INGREDIENTS = 'FETCHING_INGREDIENTS';
export const ON_ERROR = 'ON_ERROR';

export const ORDER_INIT = 'ORDER_INIT';
export const START_ORDER = 'START_ORDER';
export const ON_ORDER_SUCCESS = 'ON_ORDER_SUCCESS';
export const ON_ORDER_FAIL = 'ON_ORDER_FAIL';

export const START_FETCH_ORDERS = 'START_FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const START_AUTH = 'START_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';